{
 "title": "Qcloud CDB",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "qce_cdb_cpuuserate_max",
     "legendFormat": "{{instance_id}}[{{instance_name}}]"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "qce_cdb_memoryuserate_max",
     "legendFormat": "{{instance_id}}[{{instance_name}}]"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "qce_cdb_volumerate_max",
     "legendFormat": "{{instance_id}}[{{instance_name}}]"
    }
   ]
  },
  {
   "title": "磁盘剩余用容量【单位: M】",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "max(qce_cdb_volume_size * 1024)by(instanceid) - max(qce_cdb_capacity_max)by(instanceid)",
     "legendFormat": "{{instanceid}}"
    }
   ]
  }
 ]
}