{
 "title": "AWS RDS",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_rds_cpuutilization_maximum offset 10m",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - max(aws_rds_freeable_memory_maximum offset 10m )by(instance) / max(aws_rds_freeable_memory_total * 1024 * 1024 * 1024)by(instance) * 100",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - max(aws_rds_free_storage_space_maximum offset 10m )by(instance) / max(aws_rds_storage_space_allocated * 1024 * 1024 * 1024)by(instance) * 100",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  },
  {
   "title": "磁盘剩余容量",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "aws_rds_free_storage_space_maximum offset 10m",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  }
 ]
}