{
 "title": "ECS Detail",
 "description": "Alibaba Cloud ECS Instance Dashboard",
 "tags": [
  "ECS",
  "Detail"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": {
     "query": "label_values(aliyun_meta_ecs_info, HostName)"
    }
   },
   {
    "name": "instanceId",
    "query": {
     "query": "label_values(aliyun_meta_ecs_info{HostName=\"$hostname\"}, InstanceId)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "table-old",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "aliyun_meta_ecs_info{InstanceId=\"$instanceId\"}"
    }
   ]
  },
  {
   "title": "CPU Utilization Percent",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aliyun_acs_ecs_dashboard_CPUUtilization{instanceId=\"$instanceId\"}",
     "legendFormat": "Utilization"
    }
   ]
  },
  {
   "title": "Memory Utilization Percent",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aliyun_acs_ecs_dashboard_memory_usedutilization{instanceId=\"$instanceId\"}",
     "legendFormat": "Utilization"
    }
   ]
  },
  {
   "title": "Disk Utilization Percent",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aliyun_acs_ecs_dashboard_diskusage_utilization{instanceId=\"$instanceId\"}",
     "legendFormat": "Utilization"
    }
   ]
  },
  {
   "title": "inode Utilization Percent",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aliyun_acs_ecs_dashboard_fs_inodeutilization{instanceId=\"$instanceId\"}",
     "legendFormat": "Utilization"
    }
   ]
  },
  {
   "title": "LoadAvg",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "aliyun_acs_ecs_dashboard_load_1m{instanceId=\"$instanceId\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "aliyun_acs_ecs_dashboard_load_5m{instanceId=\"$instanceId\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "aliyun_acs_ecs_dashboard_load_15m{instanceId=\"$instanceId\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "description": "\"Actual Used\" do not include cache/buffer",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "aliyun_acs_ecs_dashboard_memory_totalspace{instanceId=\"$instanceId\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "aliyun_acs_ecs_dashboard_memory_usedspace{instanceId=\"$instanceId\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "aliyun_acs_ecs_dashboard_memory_actualusedspace{instanceId=\"$instanceId\"}",
     "legendFormat": "Actual Used"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "TCP Connections",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aliyun_acs_ecs_dashboard_net_tcpconnection{instanceId=\"$instanceId\"}",
       "legendFormat": "{{ state }}"
      }
     ]
    },
    {
     "title": "Intranet Traffic",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum(aliyun_acs_ecs_dashboard_IntranetIn{instanceId=\"$instanceId\"})",
       "legendFormat": "Rx"
      },
      {
       "expr": "sum(aliyun_acs_ecs_dashboard_IntranetOut{instanceId=\"$instanceId\"})",
       "legendFormat": "Tx"
      }
     ]
    },
    {
     "title": "Internet Traffic",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum(aliyun_acs_ecs_dashboard_InternetIn{instanceId=\"$instanceId\"})",
       "legendFormat": "Rx"
      },
      {
       "expr": "sum(aliyun_acs_ecs_dashboard_InternetOut{instanceId=\"$instanceId\"})",
       "legendFormat": "Tx"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Disk I/O",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "aliyun_acs_ecs_dashboard_DiskReadBPS{instanceId=\"$instanceId\"}",
       "legendFormat": "Read"
      },
      {
       "expr": "aliyun_acs_ecs_dashboard_DiskWriteBPS{instanceId=\"$instanceId\"}",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Disk IOPS",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "aliyun_acs_ecs_dashboard_DiskReadIOPS{instanceId=\"$instanceId\"}",
       "legendFormat": "Read"
      },
      {
       "expr": "aliyun_acs_ecs_dashboard_DiskWriteIOPS{instanceId=\"$instanceId\"}",
       "legendFormat": "Write"
      }
     ]
    }
   ]
  }
 ]
}