{
 "title": "ECS Overview",
 "tags": [
  "ECS",
  "Overview"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "1m,5m,10m,30m,1h,6h" },
   {
    "name": "zone",
    "query": {
     "query": "label_values(aliyun_meta_ecs_info, ZoneId)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "alertname=~\"ecs.*\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "P95 CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile(0.95, aliyun_acs_ecs_dashboard_CPUUtilization)",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "P95 Load",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile(0.95, aliyun_acs_ecs_dashboard_load_5m)",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "P95 Memory",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile(0.95, aliyun_acs_ecs_dashboard_memory_usedutilization)",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "CPU Pressure",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "(avg_over_time(aliyun_acs_ecs_dashboard_CPUUtilization[$interval]) > 80) * on (instanceId) group_left(VpcAttributes,HostName,InnerIpAddress) \nlabel_replace(aliyun_meta_ecs_info,\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\")"
    }
   ]
  },
  {
   "title": "Memory Pressure",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "(avg_over_time(aliyun_acs_ecs_dashboard_memory_usedutilization[$interval]) > 95) * on (instanceId) group_left(VpcAttributes,HostName,InnerIpAddress) \nlabel_replace(aliyun_meta_ecs_info,\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\")"
    }
   ]
  },
  {
   "title": "Load Pressure",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "(avg_over_time(aliyun_acs_ecs_dashboard_load_5m[$interval]) > 10) * on (instanceId) group_left(VpcAttributes,HostName,InnerIpAddress) \nlabel_replace(aliyun_meta_ecs_info,\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\")"
    }
   ]
  },
  {
   "title": "Disk Pressure",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "(avg_over_time(aliyun_acs_ecs_dashboard_diskusage_utilization[$interval]) > 90) * on (instanceId) group_left(VpcAttributes,HostName,InnerIpAddress) \nlabel_replace(aliyun_meta_ecs_info,\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\")"
    }
   ]
  },
  {
   "title": "Too Many Connections",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "(avg_over_time(aliyun_acs_ecs_dashboard_net_tcpconnection{state=\"TCP_TOTAL\"}[10m]) > 1000) * on (instanceId) group_left(VpcAttributes,HostName,InnerIpAddress) \nlabel_replace(aliyun_meta_ecs_info,\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\")"
    }
   ]
  },
  {
   "title": "Abnormal Network IO",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "(avg_over_time(aliyun_acs_ecs_dashboard_InternetOut[10m]) > 10 * 1024 * 1024) * on (instanceId) group_left(VpcAttributes,HostName,InnerIpAddress) \nlabel_replace(aliyun_meta_ecs_info,\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\")"
    }
   ]
  }
 ]
}