{
 "title": "Qcloud Redis 服务树相关",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "treeid", "query": "10,11" }
  ]
 },
 "panels": [
  {
   "title": "资源数量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max(qce_redis_mem_cpumaxutil_max ) by(instance) and  ( sum(treeinfo{tid=\"$treeid\"}) by(instance)))"
    }
   ]
  },
  { "title": "详情", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(qce_redis_mem_cpumaxutil_max ) by(instance) and  ( sum(treeinfo{tid=\"$treeid\"}) by(instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(qce_redis_mem_memmaxutil_max ) by(instance) and  ( sum(treeinfo{tid=\"$treeid\"}) by(instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}