{
 "title": "fping-v2",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "分组",
    "query": {
     "query": "label_values(up{job=\"fping-v2\"}, group)"
    }
   },
   {
    "name": "link",
    "label": "链路",
    "query": {
     "query": "label_values(up{job=\"fping-v2\"}, link)"
    }
   },
   {
    "name": "src",
    "label": "源",
    "query": {
     "query": "label_values(up{job=\"fping-v2\"}, src)"
    }
   },
   {
    "name": "dst",
    "label": "目标",
    "query": {
     "query": "label_values(up{job=\"fping-v2\"}, dst)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "网络延时(全局)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(up{job=\"fping-v2\"})",
     "legendFormat": "采集总量"
    },
    {
     "expr": "count(up{job=\"fping-v2\"}==1)",
     "legendFormat": "采集成功"
    }
   ]
  },
  {
   "title": "Ping 不通(全局)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "fping_lost_count{} / fping_sent_count * 100 == 100",
     "legendFormat": "{{dstip}} / {{link}} "
    }
   ]
  },
  {
   "title": "网络延时(全局)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "avg(fping_rtt_sum{job=\"fping-v2\"} / fping_rtt_count * 1000)by(link)",
     "legendFormat": "{{link}}"
    }
   ]
  },
  {
   "title": "网络丢包率(全局)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(fping_lost_count{job=\"fping-v2\"} / fping_sent_count * 100)by(link)",
     "legendFormat": "{{link}}"
    }
   ]
  },
  {
   "title": "网络延时(分组)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "avg(fping_rtt_sum{job=\"fping-v2\",group=~ \"$group\"} / fping_rtt_count * 1000)by(link)",
     "legendFormat": "{{link}}"
    }
   ]
  },
  {
   "title": "网络丢包率(分组)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(fping_lost_count{job=\"fping-v2\",group=~ \"$group\"} / fping_sent_count * 100)by(link)",
     "legendFormat": "{{link}}"
    }
   ]
  },
  {
   "title": "网络延迟(链路)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "fping_rtt_sum{link=~\"$link\"} / fping_rtt_count * 1000",
     "legendFormat": "{{srcip}}:{{dstip}}"
    }
   ]
  },
  {
   "title": "网络丢包率(链路)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "fping_lost_count{link=~\"$link\"} / fping_sent_count * 100",
     "legendFormat": "{{srcip}}:{{dstip}}"
    }
   ]
  },
  {
   "title": "网络延时(源)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "avg(fping_rtt_sum{job=\"fping-v2\",src =~\"$src\"} / fping_rtt_count * 1000)by(link)",
     "legendFormat": "{{link}}"
    }
   ]
  },
  {
   "title": "网络丢包率(源)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(fping_lost_count{job=\"fping-v2\",src=~ \"$src\"} / fping_sent_count * 100)by(link)",
     "legendFormat": "{{link}}"
    }
   ]
  },
  {
   "title": "网络延时(目标)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "avg(fping_rtt_sum{job=\"fping-v2\",dst =~ \"$dst\"} / fping_rtt_count * 1000)by(link)",
     "legendFormat": "{{link}}"
    }
   ]
  },
  {
   "title": "网络丢包率(目标)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(fping_lost_count{job=\"fping-v2\",dst=~ \"$dst\"} / fping_sent_count * 100)by(link)",
     "legendFormat": "{{link}}"
    }
   ]
  }
 ]
}