{
 "title": "AWS 负载均衡",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "ALB/流量",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_applicationelb_processed_bytes_maximum offset 10m",
     "legendFormat": "{{load_balancer}}"
    }
   ]
  },
  {
   "title": "ALB/当前连接数",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_applicationelb_active_connection_count_maximum offset 10m",
     "legendFormat": "{{load_balancer}}"
    }
   ]
  },
  {
   "title": "ELB/流量",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_elb_estimated_processed_bytes_maximum offset 10m",
     "legendFormat": "{{load_balancer_name}}"
    }
   ]
  },
  {
   "title": "ELB/当前连接数",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_elb_estimated_albactive_connection_count_maximum offset 10m",
     "legendFormat": "{{load_balancer_name}}"
    }
   ]
  },
  {
   "title": "NLB/流量",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_networkelb_processed_bytes_maximum offset 10m",
     "legendFormat": "{{load_balancer}}"
    }
   ]
  },
  {
   "title": "NLB/当前连接数",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_networkelb_active_flow_count_maximum offset 10m",
     "legendFormat": "{{load_balancer}}"
    }
   ]
  }
 ]
}