{
 "title": "AWS LB",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cloudmonname",
    "label": "账号-区域",
    "query": "label_values({__name__=~\"aws_applicationelb_active_connection_count_sum|aws_elb_estimated_albactive_connection_count_maximum|aws_networkelb_active_flow_count_maximum\"}, cloudmonname)"
   }
  ]
 },
 "panels": [
  {
   "title": "ALB 总数",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(sum(aws_applicationelb_active_connection_count_sum{cloudmonname=~\"$cloudmonname\"} offset 10m )by(cloudmonname,load_balancer))  "
    }
   ]
  },
  {
   "title": "ELB总数",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(sum(aws_elb_estimated_albactive_connection_count_maximum{cloudmonname=~\"$cloudmonname\"} offset 10m )by(cloudmonname,load_balancer_name))",
     "legendFormat": "{{cloudmonname}}/{{load_balancer_name}}"
    }
   ]
  },
  {
   "title": "NLB总数",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(sum(aws_networkelb_active_flow_count_maximum{cloudmonname=~\"$cloudmonname\"} offset 10m )by(cloudmonname,load_balancer))",
     "legendFormat": "{{cloudmonname}}/{{load_balancer}}"
    }
   ]
  },
  {
   "title": "ALB 后端节点数量",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_applicationelb_healthy_host_count_maximum{cloudmonname=~\"$cloudmonname\"} offset 10m)by(cloudmonname,load_balancer) ",
     "legendFormat": "{{cloudmonname}}|{{load_balancer}}"
    }
   ]
  },
  {
   "title": "ALB活跃连接数",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_applicationelb_active_connection_count_sum{cloudmonname=~\"$cloudmonname\"} offset 10m )by(cloudmonname,load_balancer)",
     "legendFormat": "{{cloudmonname}}|{{load_balancer}}"
    }
   ]
  },
  {
   "title": "ELB 后端机器数",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_elb_healthy_host_count_maximum{cloudmonname=~\"$cloudmonname\"} offset 10m )by(cloudmonname,load_balancer_name)",
     "legendFormat": "{{cloudmonname}}/{{load_balancer_name}}"
    }
   ]
  },
  {
   "title": "ELB活跃连接数",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_elb_estimated_albactive_connection_count_maximum{cloudmonname=~\"$cloudmonname\"} offset 10m )by(cloudmonname,load_balancer_name)",
     "legendFormat": "{{cloudmonname}}/{{load_balancer_name}}"
    }
   ]
  },
  {
   "title": "ELB 后端机器数",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_networkelb_healthy_host_count_maximum{cloudmonname=~\"$cloudmonname\"} offset 10m )by(cloudmonname,load_balancer)",
     "legendFormat": "{{cloudmonname}}/{{load_balancer}}"
    }
   ]
  },
  {
   "title": "NLB活跃连接数",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_networkelb_active_flow_count_maximum{cloudmonname=~\"$cloudmonname\"} offset 10m )by(cloudmonname,load_balancer)",
     "legendFormat": "{{cloudmonname}}/{{load_balancer}}"
    }
   ]
  }
 ]
}