{
 "title": "Qcloud CDB 服务树相关",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "treeid", "query": "10,11" }
  ]
 },
 "panels": [
  {
   "title": "资源数量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max(qce_cdb_cpuuserate_max ) by(instance) and  ( sum(treeinfo{tid=\"$treeid\"}) by(instance)))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "详情", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(qce_cdb_cpuuserate_max ) by(instance) and  ( sum(treeinfo{tid=\"$treeid\"}) by(instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(qce_cdb_memoryuserate_max ) by(instance) and  ( sum(treeinfo{tid=\"$treeid\"}) by(instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(qce_cdb_volumerate_max ) by(instance) and  ( sum(treeinfo{tid=\"$treeid\"}) by(instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "磁盘剩余用容量【单位: M】",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "max(qce_cdb_volume_size * 1024)by(instance) - max(qce_cdb_capacity_max)by(instance) and  ( sum(treeinfo{tid=\"$treeid\"}) by(instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}